Feat/copy modal
jobda-keychain/jobda-qa-util-web pull request #17
Opened 2022-01-12 05:51 UTC by prs176

## 복사 모달

- [ ] 베이스 모달
- [ ] 복사 모달

2022-01-12 06:08 UTC, psh5496 commented on src/components/CopyModal/CopyModal.tsx
> +    const [format, setFormat] = useState<string>('');
제네릭을 써서 타입을 명시해주셨는데, 해당 경우 제네릭이 없어도 타입 추론이 되기 때문에 딱히 필요가 없어보입니다. 스타일 차이라 상관은 없지만 형규님 컨벤션에서는 깔끔한 코드를 지향해서 타입추론이 되는 부분에서는 굳이 제네릭으로 명시를 안 해주신다고 하네요. 참고해주세요.

2022-01-12 07:27 UTC, khg0712 requested changes

2022-01-12 07:27 UTC, khg0712 commented on src/components/CopyModal/style.ts
> +export const FormatInput = styled.input`
https://mui.com/components/text-fields/

사용하는 게 더 좋지 않을까요?

2022-01-13 00:31 UTC, khg0712 commented on src/components/CopyModal/CopyModal.tsx
> +        id='filled-basic'
`id` 추가 하신 이유가 있나요?

2022-01-13 05:51 UTC, prs176 commented on src/components/CopyModal/CopyModal.tsx
> +        id='filled-basic'
삭제했습니다.

2022-01-13 07:32 UTC, merged