Feat/create environment
jobda-keychain/jobda-qa-util-web pull request #44
Opened 2022-01-17 06:52 UTC by prs176

## 환경 생성

- [ ] 환경 생성

2022-01-17 07:34 UTC, psh5496 approved these changes

2022-01-17 14:09 UTC, khg0712 requested changes

2022-01-17 14:09 UTC, khg0712 commented on src/hooks/useEnvironmentList.ts
> +const useEnvironmentList = () => {
훅 이름은 `useEnvironmentList`인데 modal과 연관된 책임도 가지고 있는 것 같네요 분리하는 게 더 좋을 것 같습니다

2022-01-17 14:09 UTC, khg0712 commented on src/hooks/useEnvironmentModal.ts
> +  const onChangeEnvironment = useCallback(
이렇게 초기화해주는 게 좋을까요?

2022-01-17 14:09 UTC, khg0712 commented on src/util/api/environment/environment.api.ts
> +  const { data } = await instance.post<void>(url, dto);
`void` 제네릭을 사용하시는 게 맞을까요?

2022-01-17 14:09 UTC, khg0712 commented on src/util/api/environment/environment.dto.ts
> +import { EPlatform } from '../../../lib/enum/platform';
@prs176 @psh5496 
`enum`인 경우에 `E` prefix를 붙이는 건 좋은 네이밍일까요?

2022-01-17 14:09 UTC, khg0712 commented on src/util/api/environment/environment.dto.ts
> +export interface ICreateEnvironmentDto {
@prs176 @psh5496 
`interface`인 경우에 `I` prefix를 붙이는 건 좋은 네이밍일까요?

2022-01-17 14:09 UTC, khg0712 commented on src/util/api/environment/environment.dto.ts
> +export interface ICreateEnvironmentDto {
@prs176 @psh5496 
DTO는 어떤 역할을 하는 객체인가요?

2022-01-18 01:02 UTC, prs176 commented on src/util/api/environment/environment.api.ts
> +  const { data } = await instance.post<void>(url, dto);
response가 없을 때는 어떤 값을 리턴하는게 좋을까요?

2022-01-18 01:58 UTC, merged